### PR TITLE
feat: add @arktoshi delegate profile

### PR DESCRIPTION
**Pull request by arktoshidotcom**

### CODE REVIEW

**Comment by qsvtr** [comment]
cool thanks @arktoshidotcom for your contribution and welcome!
if you share your rewards you can add this in your file: `rewardsSharing: true` like [here](https://github.com/unik-name/unikname-network-delegates-website/blame/7becb4c2156d152c6600b21682cb0f53dd1ec9dd/docs/delegates/110688c7e2b4ce9f369aade0e5e6d8076a5beb28066d473bcaa4f0ddb124803c/README.md#L7)

**Comment by arktoshidotcom** [comment]
> cool thanks @arktoshidotcom for your contribution and welcome!
> if you share your rewards you can add this in your file: `rewardsSharing: true` like [here](https://github.com/unik-name/unikname-network-delegates-website/blame/7becb4c2156d152c6600b21682cb0f53dd1ec9dd/docs/delegates/110688c7e2b4ce9f369aade0e5e6d8076a5beb28066d473bcaa4f0ddb124803c/README.md#L7)

I've updated my Readme.md file. Thanks @qsvtr!

**Review by qsvtr — APPROVED** [review]

**Comment by qsvtr** [comment]
last step @arktoshidotcom, it's necessary [to sign](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification) your commits :)

**Comment by arktoshidotcom** [comment]
> last step @arktoshidotcom, it's necessary [to sign](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification) your commits :)

Hi, I've jut updated proposal and verified commits.

**Pull request merged**
