### PR TITLE
TheBlackCat: update delegate payout url

### PR DESCRIPTION
**Pull request by peterjah**

### CODE REVIEW

**Review by dlecan — APPROVED** [review]

**Comment by dlecan** [comment]
@peterjah commits must be signed!

**Comment by dlecan** [comment]
thank you :-)

**Comment by dlecan** [comment]
Still one commit not signed :-(
Is it intended?

**Comment by peterjah** [comment]
> Still one commit not signed :-(
> Is it intended?

Sorry, It was garbages!

**Pull request merged**
